name: CI Frontend Angular

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm ci
        working-directory: frontend

      - name: Ejecutar pruebas
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: frontend

      - name: Construir aplicación Angular
        run: npm run build -- --configuration production
        working-directory: frontend

      - name: Construir imagen Docker
        run: docker build -t frontend-app ./frontend
